baseurl = "/"
languageCode = "en-us"
title = "Jian Cui Ph.D."
theme = "ezhil"
googleAnalytics = "UA-123-45"

copyright = "Copyright © by Jian Cui"

disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Postdoctoral associate @ [Drug Discovery Institute - University of Pittsburgh](https://upddi.pitt.edu/)"

    # description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "dark" # "dark" or "auto"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:cuij@pitt.edu"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/NaijIuc"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jian-cui-61ab121b0/"

# Enable tags.
[taxonomies]
   tag = "tags"