baseurl = "/"
languageCode = "en-us"
title = "Jian Cui Ph.D."
theme = "solar-theme-hugo"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/NaijIuc"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jian-cui-61ab121b0/"

[params]
    description = "Postdoctoral Researcher @ Drug Discovery Institute - University of Pittsburgh"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "mylogo.png"
    width = 50
    height = 50
    alt = "Logo"

