baseurl = "/"
languageCode = "en-us"
title = "Jian Cui Ph.D."
theme = "ezhil"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

copyright = "© Jian Cui"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    subtitle = "Postdoctoral Associate @  [Drug Discovery Institute - University of Pittsburgh](https://upddi.pitt.edu/)"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	
	mode = "auto" # "dark", "auto", "light"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "jcicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/NaijIuc"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jian-cui-61ab121b0/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:cuij@pitt.edu"

[taxonomies]
   tag = "tags"
